Add support of speech recognition for microphone node
node-red/node-red-ui-nodes pull request #52
Opened 2020-12-22 02:01 UTC by HiroyasuNishiyama

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes

This PR add speech recognition feature to ui_microphone node using SpeechRecognition interface of Web Speech API.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red-nodes/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

2020-12-22 21:28 UTC, dceejay requested changes
Thank you very much for adding this mode and adding all the translations.

2020-12-22 21:28 UTC, dceejay commented on node-red-node-ui-microphone/ui_microphone.html
> +                        $("#div-audio").hide();
Do you really want to hide the audio options ? they affect length of recording and whether it's press to talk or click to start then click to stop - both of which would also make sense for Speech to text I think ?

2020-12-22 21:28 UTC, dceejay commented on node-red-node-ui-microphone/ui_microphone.html
>              if (this.press === undefined) {
You also need an if mode is undefined check for existing nodes that don't have this set or the select box will start as blank.

2020-12-22 21:30 UTC, dceejay commented on node-red-node-ui-microphone/README.md
> +  - Firefox : SpeechRecognition needs to be enabled (about:config -> `media.webspeech.recognition.enable`).
Is there a simple way (without having to test every useragent etc) to detect if SpeechRecognition is allowed/enabled ? such that we could then hide the option if not ? (Though I guess for Firefox it would then hint that it could be enabled if wanted...)  - Maybe we want to repeat this tip in the edit confg ?

2020-12-22 21:35 UTC, dceejay commented
Is it also worth looking at adding a flag (this time under speech mode only - for continuous operation - https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/continuous  -or maybe that should possible the default when in click to start and click to stop mode... ie so you get streamed results while in that mode.

2020-12-23 15:22 UTC, HiroyasuNishiyama commented on node-red-node-ui-microphone/ui_microphone.html
> +                        $("#div-audio").hide();
OK. I'll add support for these options also for speech recognition mode.

2020-12-23 15:22 UTC, HiroyasuNishiyama commented on node-red-node-ui-microphone/ui_microphone.html
>              if (this.press === undefined) {
Thank you. Will add check as you suggested.

2020-12-23 15:26 UTC, HiroyasuNishiyama commented on node-red-node-ui-microphone/README.md
> +  - Firefox : SpeechRecognition needs to be enabled (about:config -> `media.webspeech.recognition.enable`).
Current implementation checks existence of `SpeechRecognition` interface, though on editor side, and disables speech recognition mode if not available.

2020-12-23 15:36 UTC, HiroyasuNishiyama commented
> Is it also worth looking at adding a flag (under speech mode only) - for interim results operation - https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/interimResults -or maybe that should possible the default when in click to start and click to stop mode... ie so you get streamed results while in that mode ?

In our original implementation, specifying the interim results option would display the intermediate recognition results on the dashboard.
I think it can be used for such purposes.
However, if the node outputs interim results, distinguishing between the final and intermediate results is needed.
I would like to suggest the node outputs interim results to second output port if the interim results option is specified.

2020-12-25 13:04 UTC, HiroyasuNishiyama commented
Hi. Updated speech recognition mode to use same button mode of audio input with fixes you pointed out.
Also added example flows for both mode.

2020-12-26 12:32 UTC, dceejay commented on node-red-node-ui-microphone/ui_microphone.html
> +                        $("#div-audio").hide();
Thanks - as it was you could set it either way  when in the non-reco mode and then switch to reco and the button behaviour would be as you had set it but couldn't be changed.

2020-12-26 12:34 UTC, dceejay commented on node-red-node-ui-microphone/README.md
> +  - Firefox : SpeechRecognition needs to be enabled (about:config -> `media.webspeech.recognition.enable`).
interesting thought... I suppose in practise the runtime browser may well be different from the browser used for editing... I have no good solution for that, apart from ensuring the developer is aware of the possibility.

2020-12-26 12:40 UTC, dceejay commented
Yes - I think showing intermediate results on the dashboard is one use case - but that could be done via the backend - - IE don't implement in the node itself - if the user wants it they could feed the info back to another widget. I think there are other use cases where you may want ongoing data fed back. I don't think the node / reco engine will handle both modes at once so I don't know how a second output could work. Though once the reco has stopped presumable we can send a done ? so you know the microphone is no longer expected to send more.

2020-12-28 09:38 UTC, HiroyasuNishiyama commented on node-red-node-ui-microphone/README.md
> +  - Firefox : SpeechRecognition needs to be enabled (about:config -> `media.webspeech.recognition.enable`).
I think that ui_audio node have a similar implementation to create a voice list.

2020-12-28 10:27 UTC, HiroyasuNishiyama commented
> Though once the reco has stopped presumable we can send a done ? so you know the microphone is no longer expected to send more.

Changed to set `done` property to `true` instead of sending a message to second port if interim flag is set.

2020-12-28 10:30 UTC, HiroyasuNishiyama commented on node-red-node-ui-microphone/ui_microphone.html
> +                        $("#div-audio").hide();
> ... but couldn't be changed.

Does this mean that there is some issue on your side?

2020-12-28 10:39 UTC, dceejay commented on node-red-node-ui-microphone/ui_microphone.html
> +                        $("#div-audio").hide();
not now that the option is available when in reco mode.

2020-12-28 10:41 UTC, dceejay commented on node-red-node-ui-microphone/README.md
> +  - Firefox : SpeechRecognition needs to be enabled (about:config -> `media.webspeech.recognition.enable`).
yes - my next question was going to be about languages... is it selected by the browser language or user configuration ?

2020-12-28 12:08 UTC, HiroyasuNishiyama commented on node-red-node-ui-microphone/README.md
> +  - Firefox : SpeechRecognition needs to be enabled (about:config -> `media.webspeech.recognition.enable`).
Current implementation uses default browser language.  
`SpeechRecognition` interface have `lang` property that accepts language to be recognized. 
However, it do not provides list of languages that can be recognized.

2020-12-28 15:49 UTC, dceejay commented
Looks good now - Using Done works nicely - thank you. only wrinkle I can see is if I drag on a new node and set to reco mode the default time is 0 seconds. It should default to some useful value (maybe 5 to be consistent with the audio mode. ? )

2020-12-28 15:53 UTC, dceejay commented
I'm going to merge this as-is and we can work on it from there in master. I won't publish it just yet.

2020-12-28 15:54 UTC, merged

2020-12-28 23:47 UTC, HiroyasuNishiyama commented
> I think leaving as 0 doesn't make sense unless you have intermediate results on by default... which we don't want (I think).

`SpeechRecognition` interface outputs a final result for each phrase (at least for Japanese recognition). The interim result will change before fixed as final result.  
For this reason, I intentionally set the default value to 0 in speech recognition mode.